#!/bin/bash
# int-or-string.sh
COUNTER=1
for ((n=0;n<1;n++)); do
  echo "CONTADOR: $COUNTER"

  python3.5 ./Python/waiter.py &&
  python ./Python/runner.py $((COUNTER+1))
  COUNTER=$((COUNTER+1))
done
